### ISSUE TITLE
Absolute depth (metric depth)

### ISSUE THREAD

**Issue by AbbosAbdullayev** [Aradhye2002/EcoDepth#10]
thanks for the awesome contribution on monocular depth estimation.  Does the model predict the relative depth map? is it possible to get actual distances (in meters) from the predicted depth map? thank you for your response

**Comment by AbbosAbdullayev** [comment]
@Aradhye2002, thank you very much for your quick response. I followed the README of your work and downloaded the required checkpoint files. However, I'm encountering an out-of-memory issue when performing inference on a single arbitrary image. My environment consists of an RTX GPU with 12GB, which I believe should be sufficient for inference. Could I have overlooked something? I'm testing under Kitti outdoor conditions using the vkitti model (4GB) and transforms (v1-5**) (4GB). Can you provide some suggestions?

**Comment by visualax** [comment]
> @Aradhye2002, thank you very much for your quick response. I followed the README of your work and downloaded the required checkpoint files. However, I'm encountering an out-of-memory issue when performing inference on a single arbitrary image. My environment consists of an RTX GPU with 12GB, which I believe should be sufficient for inference. Could I have overlooked something? I'm testing under Kitti outdoor conditions using the vkitti model (4GB) and transforms (v1-5**) (4GB). Can you provide some suggestions?

With the same kitti model 4GB and SD ckpt 4GB, the model fails with a single image on an A10G with 24GiB. Also tried everything to reduce memory, nothing works. This model requires a 32GiB GPU to be safe.

**Comment by Aradhye2002** [comment]
Hi @AbbosAbdullayev, can you please take a look at https://github.com/Aradhye2002/EcoDepth/issues/6#issuecomment-2041351542 which mentions a fix for reducing GPU memory consumption? In case it still doesn't work, can you report the value of the `max_area` variable that you are using? Ideally as you would reduce the `max_area` variable to zero, the memory requirement should go to 4GB + 4GB = 8 GB (for the vkitti model and stable diffusion model resp.) and the performance should drop to 0. Since your capacity is 12 GB, you can do inference with a non-zero `max_area` variable value. I would advise you to try different values of `max_area` to find the largest one (in order to maximize performance) that does not result in an OOM error.
