### ISSUE TITLE
CUDA MEMORY ERROR!!!

### ISSUE THREAD

**Issue by PreyumKr** [Aradhye2002/EcoDepth#18]
Sir, I wanted to know how much GPU size is required minimal to run this model. I was trying to run the model but let alone training, I am getting memory errors for inferencing too using the model checkpoints. I am currently using a 16GB GPU, Is it even possible to run this model and train it further in this GPU size?

**Comment by Aradhye2002** [comment]
Hi @PreyumKr, you can easily run the model on a 16GB GPU. You just need to change the max_area variable in the infer.py script which has been currently set to 1000*720. This essentially controls the resolution of the image that is sent to the model by specifying the number of pixels. It is set to this value to maximally utilize a 32GB GPU, due to which you are getting OOM. Please try to set the max_area variable to a lower value like 1000*180 and let me know if it works.

**Comment by PreyumKr** [comment]
Sorry for the late reply. Thanks for the help. It fixed the inference part. I was able to run inference in the size of 1000*360 as well.  Can you tell me if the same is possible to train the model with the dataset? During the training as well the code gives me CUDA OUT OF MEMORY ERROR!!!
